### ISSUE TITLE
error after executing pham_band.py script

### ISSUE THREAD

**Issue by SreenivasIKST** [QijingZheng/phonon_angular_momentum#1]
Hi, I am ending with the following error after executing pham_band.py script

![image](https://github.com/QijingZheng/phonon_angular_momentum/assets/41950252/8484e619-339f-4011-b109-1dc938b7dbd9)

**Comment by QijingZheng** [comment]
Hi

The error message suggests that you are using a old version of matplotlib.

Best
Qijing
